platform :ios, '9.0'

target 'TrulyMadlyDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
   pod 'Google/SignIn'
  # Pods for TrulyMadlyDemo

  target 'TrulyMadlyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrulyMadlyDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
